/* =========================================================
   settings.gradle  —  تنظیمات پروژه Gradle
   مسیر: template/settings.gradle
   ========================================================= */

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "RoshaTemplate"
include ':app'
