# =========================================================
# gradle.properties
# =========================================================

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.enableJetifier=false
android.enableR8.fullMode=true

# ===== نمایش واضح خطاها =====
android.nonTransitiveRClass=false
android.nonFinalResIds=false

# ===== اجازه بده منابع خطادار build رو متوقف نکنن =====
android.aapt2.forceCompile=true
